export const momentum = [
  {
    id: "momentum-01",
    title: "Benevides",
    location: "Botucatu, SP",
    directory: "momentum/benevides",
    category: "Momentum",
    description:
      "Projeto desenvolvido com excelência técnica e atenção aos detalhes, garantindo qualidade e satisfação do cliente.",
    client: "Benevides",
    conclusion_year: 2026,
    services: ["Projeto", "Gerenciamento", "Acompanhamento"],
  },
  {
    id: "momentum-02",
    title: "Carvalho",
    location: "Botucatu, SP",
    directory: "momentum/carvalho",
    category: "Momentum",
    description:
      "Projeto desenvolvido com excelência técnica e atenção aos detalhes, garantindo qualidade e satisfação do cliente.",
    client: "Carvalho",
    conclusion_year: 2026,
    services: ["Projeto", "Gerenciamento", "Acompanhamento"],
  },
  {
    id: "momentum-03",
    title: "Diversos",
    location: "Botucatu, SP",
    directory: "momentum/diversos",
    category: "Momentum",
    description:
      "Projeto desenvolvido com excelência técnica e atenção aos detalhes, garantindo qualidade e satisfação do cliente.",
    client: "Diversos",
    conclusion_year: 2026,
    services: ["Projeto", "Gerenciamento", "Acompanhamento"],
  },
  {
    id: "momentum-04",
    title: "Fernandes",
    location: "Botucatu, SP",
    directory: "momentum/fernandes",
    category: "Momentum",
    description:
      "Projeto desenvolvido com excelência técnica e atenção aos detalhes, garantindo qualidade e satisfação do cliente.",
    client: "Fernandes",
    conclusion_year: 2026,
    services: ["Projeto", "Gerenciamento", "Acompanhamento"],
  },
  {
    id: "momentum-05",
    title: "Gray",
    location: "Botucatu, SP",
    directory: "momentum/gray",
    category: "Momentum",
    description:
      "Projeto desenvolvido com excelência técnica e atenção aos detalhes, garantindo qualidade e satisfação do cliente.",
    client: "Gray",
    conclusion_year: 2026,
    services: ["Projeto", "Gerenciamento", "Acompanhamento"],
  },
  {
    id: "momentum-06",
    title: "Jacques",
    location: "Botucatu, SP",
    directory: "momentum/jacques",
    category: "Momentum",
    description:
      "Projeto desenvolvido com excelência técnica e atenção aos detalhes, garantindo qualidade e satisfação do cliente.",
    client: "Jacques",
    conclusion_year: 2026,
    services: ["Projeto", "Gerenciamento", "Acompanhamento"],
  },
  {
    id: "momentum-07",
    title: "Luiz",
    location: "Botucatu, SP",
    directory: "momentum/luiz",
    category: "Momentum",
    description:
      "Projeto desenvolvido com excelência técnica e atenção aos detalhes, garantindo qualidade e satisfação do cliente.",
    client: "Luiz",
    conclusion_year: 2026,
    services: ["Projeto", "Gerenciamento", "Acompanhamento"],
  },
  {
    id: "momentum-08",
    title: "Maciel",
    location: "Botucatu, SP",
    directory: "momentum/maciel",
    category: "Momentum",
    description:
      "Projeto desenvolvido com excelência técnica e atenção aos detalhes, garantindo qualidade e satisfação do cliente.",
    client: "Maciel",
    conclusion_year: 2026,
    services: ["Projeto", "Gerenciamento", "Acompanhamento"],
  },
  {
    id: "momentum-09",
    title: "Oliveira",
    location: "Botucatu, SP",
    directory: "momentum/oliveira",
    category: "Momentum",
    description:
      "Projeto desenvolvido com excelência técnica e atenção aos detalhes, garantindo qualidade e satisfação do cliente.",
    client: "Oliveira",
    conclusion_year: 2026,
    services: ["Projeto", "Gerenciamento", "Acompanhamento"],
  },
  {
    id: "momentum-10",
    title: "Pires",
    location: "Botucatu, SP",
    directory: "momentum/pires",
    category: "Momentum",
    description:
      "Projeto desenvolvido com excelência técnica e atenção aos detalhes, garantindo qualidade e satisfação do cliente.",
    client: "Pires",
    conclusion_year: 2026,
    services: ["Projeto", "Gerenciamento", "Acompanhamento"],
  },
  {
    id: "momentum-11",
    title: "Pressotto",
    location: "Botucatu, SP",
    directory: "momentum/pressotto",
    category: "Momentum",
    description:
      "Projeto desenvolvido com excelência técnica e atenção aos detalhes, garantindo qualidade e satisfação do cliente.",
    client: "Pressotto",
    conclusion_year: 2026,
    services: ["Projeto", "Gerenciamento", "Acompanhamento"],
  },
  {
    id: "momentum-12",
    title: "Silva",
    location: "Botucatu, SP",
    directory: "momentum/silva",
    category: "Momentum",
    description:
      "Projeto desenvolvido com excelência técnica e atenção aos detalhes, garantindo qualidade e satisfação do cliente.",
    client: "Silva",
    conclusion_year: 2026,
    services: ["Projeto", "Gerenciamento", "Acompanhamento"],
  },
];
