export const momentum = [
  {
    id: "momentum-01",
    title: "Benevides",
    location: "Botucatu, SP",
    directory: "momentum/benevides",
    category: "Momentum",
    description:
      "Projeto executado com alto padrão técnico e cuidado minucioso, garantindo solidez e satisfação do cliente.",
    client: "Benevides",
    conclusion_year: 2026,
    services: ["Projeto", "Gerenciamento", "Acompanhamento"],
  },
  {
    id: "momentum-02",
    title: "Carvalho",
    location: "Botucatu, SP",
    directory: "momentum/carvalho",
    category: "Momentum",
    description:
      "Projeto conduzido com abordagem moderna e atenção criteriosa, assegurando eficiência e confiança ao cliente.",
    client: "Carvalho",
    conclusion_year: 2026,
    services: ["Projeto", "Gerenciamento", "Acompanhamento"],
  },
  {
    id: "momentum-03",
    title: "Diversos",
    location: "Botucatu, SP",
    directory: "momentum/diversos",
    category: "Momentum",
    description:
      "Projeto desenvolvido com soluções inteligentes e olhar detalhista, garantindo desempenho e satisfação do cliente.",
    client: "Diversos",
    conclusion_year: 2026,
    services: ["Projeto", "Gerenciamento", "Acompanhamento"],
  },
  {
    id: "momentum-04",
    title: "Fernandes",
    location: "Botucatu, SP",
    directory: "momentum/fernandes",
    category: "Momentum",
    description:
      "Projeto realizado com precisão construtiva e atenção refinada, assegurando qualidade e confiança ao cliente.",
    client: "Fernandes",
    conclusion_year: 2026,
    services: ["Projeto", "Gerenciamento", "Acompanhamento"],
  },
  {
    id: "momentum-05",
    title: "Gray",
    location: "Botucatu, SP",
    directory: "momentum/gray",
    category: "Momentum",
    description:
      "Projeto elaborado com técnica apurada e foco minucioso, garantindo eficiência e satisfação do cliente.",
    client: "Gray",
    conclusion_year: 2026,
    services: ["Projeto", "Gerenciamento", "Acompanhamento"],
  },
  {
    id: "momentum-06",
    title: "Jacques",
    location: "Botucatu, SP",
    directory: "momentum/jacques",
    category: "Momentum",
    description:
      "Projeto estruturado com método rigoroso e atenção constante, assegurando desempenho e tranquilidade ao cliente.",
    client: "Jacques",
    conclusion_year: 2026,
    services: ["Projeto", "Gerenciamento", "Acompanhamento"],
  },
  {
    id: "momentum-07",
    title: "Luiz",
    location: "Botucatu, SP",
    directory: "momentum/luiz",
    category: "Momentum",
    description:
      "Projeto executado com padrão elevado e cuidado dedicado, garantindo segurança e satisfação do cliente.",
    client: "Luiz",
    conclusion_year: 2026,
    services: ["Projeto", "Gerenciamento", "Acompanhamento"],
  },
  {
    id: "momentum-08",
    title: "Maciel",
    location: "Botucatu, SP",
    directory: "momentum/maciel",
    category: "Momentum",
    description:
      "Projeto conduzido com excelência operacional e atenção minuciosa, assegurando qualidade e confiança ao cliente.",
    client: "Maciel",
    conclusion_year: 2026,
    services: ["Projeto", "Gerenciamento", "Acompanhamento"],
  },
  {
    id: "momentum-09",
    title: "Oliveira",
    location: "Botucatu, SP",
    directory: "momentum/oliveira",
    category: "Momentum",
    description:
      "Projeto desenvolvido com abordagem eficiente e foco detalhado, garantindo desempenho e satisfação do cliente.",
    client: "Oliveira",
    conclusion_year: 2026,
    services: ["Projeto", "Gerenciamento", "Acompanhamento"],
  },
  {
    id: "momentum-10",
    title: "Pires",
    location: "Botucatu, SP",
    directory: "momentum/pires",
    category: "Momentum",
    description:
      "Projeto realizado com alto nível construtivo e atenção cuidadosa, assegurando qualidade e tranquilidade ao cliente.",
    client: "Pires",
    conclusion_year: 2026,
    services: ["Projeto", "Gerenciamento", "Acompanhamento"],
  },
  {
    id: "momentum-11",
    title: "Pressotto",
    location: "Botucatu, SP",
    directory: "momentum/pressotto",
    category: "Momentum",
    description:
      "Projeto elaborado com soluções modernas e atenção criteriosa, garantindo eficiência e satisfação do cliente.",
    client: "Pressotto",
    conclusion_year: 2026,
    services: ["Projeto", "Gerenciamento", "Acompanhamento"],
  },
  {
    id: "momentum-12",
    title: "Silva",
    location: "Botucatu, SP",
    directory: "momentum/silva",
    category: "Momentum",
    description:
      "Projeto conduzido com técnica avançada e cuidado nos detalhes, assegurando qualidade e confiança ao cliente.",
    client: "Silva",
    conclusion_year: 2026,
    services: ["Projeto", "Gerenciamento", "Acompanhamento"],
  },
];
