export const allConstructions = [
  // COMERCIAIS
  {
    id: "1",
    title: "Clínica",
    location: "Botucatu, SP",
    image: "clinica",
    category: "Comercial",
    description:
      "Projeto desenvolvido com excelência técnica e atenção aos detalhes, garantindo qualidade e satisfação do cliente.",
    client: "Clínica",
    conclusion_year: 2026,
    area: "N/A",
    services: ["Projeto", "Gerenciamento", "Acompanhamento"],
  },
  {
    id: "2",
    title: "Clínica Odontológica",
    location: "Botucatu, SP",
    image: "clinica_odontologica",
    category: "Comercial",
    description:
      "Projeto desenvolvido com excelência técnica e atenção aos detalhes, garantindo qualidade e satisfação do cliente.",
    client: "Clínica Odontológica",
    conclusion_year: 2026,
    area: "N/A",
    services: ["Projeto", "Gerenciamento", "Acompanhamento"],
  },
  {
    id: "3",
    title: "Salas Comerciais e Lojas",
    location: "Botucatu, SP",
    image: "salas_comerciais_e_lojas",
    category: "Comercial",
    description:
      "Projeto desenvolvido com excelência técnica e atenção aos detalhes, garantindo qualidade e satisfação do cliente.",
    client: "Salas Comerciais e Lojas",
    conclusion_year: 2026,
    area: "N/A",
    services: ["Projeto", "Gerenciamento", "Acompanhamento"],
  },
  // RESIDENCIAIS
  {
    id: "4",
    title: "Outros Botucatu",
    location: "Botucatu, SP",
    image: "outros_botucatu",
    category: "Residencial",
    description:
      "Projeto desenvolvido com excelência técnica e atenção aos detalhes, garantindo qualidade e satisfação do cliente.",
    client: "Outros Botucatu",
    conclusion_year: 2026,
    area: "N/A",
    services: ["Projeto", "Gerenciamento", "Acompanhamento"],
  },
  {
    id: "5",
    title: "Parque das Cascatas",
    location: "Botucatu, SP",
    image: "parque_das_cascatas",
    category: "Residencial",
    description:
      "Projeto desenvolvido com excelência técnica e atenção aos detalhes, garantindo qualidade e satisfação do cliente.",
    client: "Parque das Cascatas",
    conclusion_year: 2026,
    area: "N/A",
    services: ["Projeto", "Gerenciamento", "Acompanhamento"],
  },
  {
    id: "6",
    title: "Parque Laguna",
    location: "Botucatu, SP",
    image: "parque_laguna",
    category: "Residencial",
    description:
      "Projeto desenvolvido com excelência técnica e atenção aos detalhes, garantindo qualidade e satisfação do cliente.",
    client: "Parque Laguna",
    conclusion_year: 2026,
    area: "N/A",
    services: ["Projeto", "Gerenciamento", "Acompanhamento"],
  },
  {
    id: "7",
    title: "Spazio Verde",
    location: "Botucatu, SP",
    image: "spazio_verde",
    category: "Residencial",
    description:
      "Projeto desenvolvido com excelência técnica e atenção aos detalhes, garantindo qualidade e satisfação do cliente.",
    client: "Spazio Verde",
    conclusion_year: 2026,
    area: "N/A",
    services: ["Projeto", "Gerenciamento", "Acompanhamento"],
  },
  {
    id: "8",
    title: "Terras Altas",
    location: "Botucatu, SP",
    image: "terras_altas",
    category: "Residencial",
    description:
      "Projeto desenvolvido com excelência técnica e atenção aos detalhes, garantindo qualidade e satisfação do cliente.",
    client: "Terras Altas",
    conclusion_year: 2026,
    area: "N/A",
    services: ["Projeto", "Gerenciamento", "Acompanhamento"],
  },
  // INDUSTRIAIS
  {
    id: "9",
    title: "Caio Induscar",
    location: "Botucatu, SP",
    image: "caio_induscar",
    category: "Industrial",
    description:
      "Projeto desenvolvido com excelência técnica e atenção aos detalhes, garantindo qualidade e satisfação do cliente.",
    client: "Caio Induscar",
    conclusion_year: 2026,
    area: "N/A",
    services: ["Projeto", "Gerenciamento", "Acompanhamento"],
  },
  {
    id: "10",
    title: "Moura Leite",
    location: "Botucatu, SP",
    image: "moura_leite",
    category: "Industrial",
    description:
      "Projeto desenvolvido com excelência técnica e atenção aos detalhes, garantindo qualidade e satisfação do cliente.",
    client: "Moura Leite",
    conclusion_year: 2026,
    area: "N/A",
    services: ["Projeto", "Gerenciamento", "Acompanhamento"],
  },
  {
    id: "11",
    title: "Vetroresina",
    location: "Botucatu, SP",
    image: "vetroresina",
    category: "Industrial",
    description:
      "Projeto desenvolvido com excelência técnica e atenção aos detalhes, garantindo qualidade e satisfação do cliente.",
    client: "Vetroresina",
    conclusion_year: 2026,
    area: "N/A",
    services: ["Projeto", "Gerenciamento", "Acompanhamento"],
  },
  // GOVERNAMENTAIS
  {
    id: "12",
    title: "Creche",
    location: "Botucatu, SP",
    image: "creche",
    category: "Governamental",
    description:
      "Projeto desenvolvido com excelência técnica e atenção aos detalhes, garantindo qualidade e satisfação do cliente.",
    client: "Creche",
    conclusion_year: 2026,
    area: "N/A",
    services: ["Projeto", "Gerenciamento", "Acompanhamento"],
  },
  // MOMENTUM
  {
    id: "13",
    title: "Ninho Verde II - Pardinho",
    location: "Botucatu, SP",
    image: "ninho_verde_ii__pardinho",
    category: "Momentum",
    description:
      "Projeto desenvolvido com excelência técnica e atenção aos detalhes, garantindo qualidade e satisfação do cliente.",
    client: "Ninho Verde II - Pardinho",
    conclusion_year: 2026,
    area: "N/A",
    services: ["Projeto", "Gerenciamento", "Acompanhamento"],
  },
  {
    id: "14",
    title: "Riviera Santa Cristina I - Arandu",
    location: "Botucatu, SP",
    image: "riviera_santa_cristina_i__arandu",
    category: "Momentum",
    description:
      "Projeto desenvolvido com excelência técnica e atenção aos detalhes, garantindo qualidade e satisfação do cliente.",
    client: "Riviera Santa Cristina I - Arandu",
    conclusion_year: 2026,
    area: "N/A",
    services: ["Projeto", "Gerenciamento", "Acompanhamento"],
  },
  {
    id: "15",
    title: "Riviera Santa Cristina XIII - Paranapanema",
    location: "Botucatu, SP",
    image: "riviera_santa_cristina_xiii__paranapanema",
    category: "Momentum",
    description:
      "Projeto desenvolvido com excelência técnica e atenção aos detalhes, garantindo qualidade e satisfação do cliente.",
    client: "Riviera Santa Cristina XIII - Paranapanema",
    conclusion_year: 2026,
    area: "N/A",
    services: ["Projeto", "Gerenciamento", "Acompanhamento"],
  },
  {
    id: "16",
    title: "Santa Bárbara Resort Residence",
    location: "Botucatu, SP",
    image: "santa_barbara_resor_residence",
    category: "Momentum",
    description:
      "Projeto desenvolvido com excelência técnica e atenção aos detalhes, garantindo qualidade e satisfação do cliente.",
    client: "Santa Bárbara Resort Residence",
    conclusion_year: 2026,
    area: "N/A",
    services: ["Projeto", "Gerenciamento", "Acompanhamento"],
  },
  // PROJETOS 3D
  {
    id: "17",
    title: "Projetos 3D",
    location: "Botucatu, SP",
    image: "projetos_3d",
    category: "Projetos 3D",
    description:
      "Projeto desenvolvido com excelência técnica e atenção aos detalhes, garantindo qualidade e satisfação do cliente.",
    client: "Projetos 3D",
    conclusion_year: 2026,
    area: "N/A",
    services: ["Projeto", "Gerenciamento", "Acompanhamento"],
  },
];
