export const allConstructions = [
  {
    id: "1",
    title: "AAF Botucatu",
    location: "Botucatu, SP",
    image: "ferroviaria",
    category: "Comercial",
  },
  {
    id: "2",
    title: "Ninho Verde ",
    location: "Botucatu, SP",
    image: "ninho_verde_eliana_pires",
    category: "Residencial",
  },
  {
    id: "3",
    title: "Ninho Verde",
    location: "Botucatu, SP",
    image: "ninho_verde_fabio",
    category: "Residencial",
  },
  {
    id: "4",
    title: "Ninho Verde",
    location: "Botucatu, SP",
    image: "ninho_verde_mauricio",
    category: "Residencial",
  },
  {
    id: "5",
    title: "Ninho Verde",
    location: "Botucatu, SP",
    image: "ninho_verde_patricia",
    category: "Residencial",
  },
  {
    id: "6",
    title: "Ninho Verde",
    location: "Botucatu, SP",
    image: "ninho_verde_patricia_aparecida",
    category: "Residencial",
  },
  {
    id: "7",
    title: "Ninho Verde",
    location: "Botucatu, SP",
    image: "ninho_verde_ricardo",
    category: "Residencial",
  },
  {
    id: "8",
    title: "Ninho Verde",
    location: "Botucatu, SP",
    image: "ninho_verde_robin",
    category: "Residencial",
  },
  {
    id: "9",
    title: "Parque das Cascatas",
    location: "Botucatu, SP",
    image: "parque_das_cascatas",
    category: "Residencial",
  },
  {
    id: "10",
    title: "Vale do Sol",
    location: "Botucatu, SP",
    image: "vale_do_sol",
    category: "Residencial",
  },
  {
    id: "11",
    title: "Edifício Comercial Centro",
    location: "São Paulo, SP",
    image: "ferroviaria",
    category: "Comercial",
  },
  {
    id: "12",
    title: "Shopping Boulevard",
    location: "Campinas, SP",
    image: "ferroviaria",
    category: "Comercial",
  },
  {
    id: "13",
    title: "Torre Empresarial Alphaville",
    location: "Barueri, SP",
    image: "ferroviaria",
    category: "Comercial",
  },
  {
    id: "14",
    title: "Galpão Industrial Logística",
    location: "Jundiaí, SP",
    image: "vale_do_sol",
    category: "Industrial",
  },
  {
    id: "15",
    title: "Fábrica de Alimentos",
    location: "Sorocaba, SP",
    image: "parque_das_cascatas",
    category: "Industrial",
  },
  {
    id: "16",
    title: "Centro de Distribuição",
    location: "Guarulhos, SP",
    image: "ninho_verde_robin",
    category: "Industrial",
  },
  {
    id: "17",
    title: "Ponte Rodoviária BR-101",
    location: "Ribeirão Preto, SP",
    image: "ninho_verde_ricardo",
    category: "Infraestrutura",
  },
  {
    id: "18",
    title: "Estação de Tratamento de Água",
    location: "Piracicaba, SP",
    image: "ninho_verde_patricia_aparecida",
    category: "Infraestrutura",
  },
  {
    id: "19",
    title: "Terminal Rodoviário Municipal",
    location: "Santos, SP",
    image: "ninho_verde_mauricio",
    category: "Infraestrutura",
  },
  {
    id: "20",
    title: "Condomínio Jardim das Flores",
    location: "Itu, SP",
    image: "ninho_verde_fabio",
    category: "Residencial",
  },
];
